/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidemo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronnie
 */
public class MainApp extends javax.swing.JFrame
{
    public FileManager manager = new FileManager();  //Create a FileManager object.
    /**
     * Creates new form MainApp
     */
    public MainApp()
    {
        initComponents();
        
        //Add sales buttons to a group so only one is checked at a time
        salesButtonGroup.add(salesButtonNorth);
        salesButtonGroup.add(salesButtonSouth);
        salesButtonGroup.add(salesButtonEast);
        salesButtonGroup.add(salesButtonWest);
        
        //Make the Enter button invisible
        //btnEnter.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        salesButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        btnQuit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOfficeSold = new javax.swing.JTextField();
        txtBooksSold = new javax.swing.JTextField();
        txtPaperSold = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        salesButtonNorth = new javax.swing.JRadioButton();
        salesButtonSouth = new javax.swing.JRadioButton();
        salesButtonEast = new javax.swing.JRadioButton();
        salesButtonWest = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        textArea = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextArea();
        txtRepID = new javax.swing.JTextField();
        txtError = new javax.swing.JTextField();
        checkPhone = new javax.swing.JCheckBox();
        checkEmail = new javax.swing.JCheckBox();
        checkVisit = new javax.swing.JCheckBox();
        btnEvaluate = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuitActionPerformed(evt);
            }
        });

        jLabel3.setText("Rep ID:");

        jLabel4.setText("Office Supplies Sold:  $");

        jLabel5.setText("Books Sold                  $");

        jLabel6.setText("Paper Sold                  $");

        jLabel7.setText("Sales District");

        salesButtonNorth.setText("North");

        salesButtonSouth.setText("South");

        salesButtonEast.setText("East");

        salesButtonWest.setText("West");

        jLabel8.setText("Contact Via");

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEnterActionPerformed(evt);
            }
        });

        outputText.setColumns(20);
        outputText.setRows(5);
        textArea.setViewportView(outputText);

        txtError.setEditable(false);

        checkPhone.setText("Phone");

        checkEmail.setText("Email");

        checkVisit.setText("Visit");

        btnEvaluate.setText("Evaluate");
        btnEvaluate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEvaluateActionPerformed(evt);
            }
        });

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(checkPhone)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(salesButtonNorth)
                                        .addComponent(salesButtonSouth)
                                        .addComponent(salesButtonEast))
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(checkEmail)
                                        .addComponent(checkVisit))))
                            .addComponent(salesButtonWest)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDisplay)
                            .addComponent(btnQuit))))
                .addGap(18, 18, 18)
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtLastName))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(txtRepID))))
                        .addGap(67, 67, 67)
                        .addComponent(btnEnter)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOfficeSold, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPaperSold)
                                    .addComponent(txtBooksSold))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnEvaluate)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRepID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOfficeSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBooksSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPaperSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesButtonNorth)
                            .addComponent(checkPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesButtonSouth)
                            .addComponent(checkEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesButtonEast)
                            .addComponent(checkVisit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salesButtonWest)
                        .addGap(57, 57, 57)
                        .addComponent(btnDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                        .addComponent(btnQuit))
                    .addComponent(textArea))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuitActionPerformed
    {//GEN-HEADEREND:event_btnQuitActionPerformed
        //Quit the application.
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnterActionPerformed
    {//GEN-HEADEREND:event_btnEnterActionPerformed
        boolean isValid;
        double total = 0;
        
        //Create a new sales rep and populate the object's variables.
        SalesRep rep = new SalesRep();
        
        rep.setRepID(txtRepID.getText());
        rep.setfName(txtFirstName.getText());
        rep.setlName(txtLastName.getText());
        rep.setOfficeSold(txtOfficeSold.getText());
        rep.setBooksSold(txtBooksSold.getText());
        rep.setPaperSold(txtPaperSold.getText());
        
        
        if (salesButtonNorth.isSelected())
        {
            rep.setSalesDistrict("NORTH");
        }else if (salesButtonSouth.isSelected())
        {
            rep.setSalesDistrict("SOUTH");
        }else if (salesButtonEast.isSelected())
        {
            rep.setSalesDistrict("EAST");
        }else if (salesButtonWest.isSelected())
        {
            rep.setSalesDistrict("WEST");
        }else
        {
            rep.setSalesDistrict("NONE");
        }
        
        if (checkPhone.isSelected())
        {
            rep.setContactPhone(true);
            System.out.println("Phone Selected");
        }
        if (checkEmail.isSelected())
        {
            rep.setContactEmail(true);
            System.out.println("Email Selected");
        }
        if (checkVisit.isSelected())
        {
            rep.setContactEmail(true);
            System.out.println("Visit Selected");
        }
            
        //Ensure that all dollar amounts are doubles
        try
        {
             double officeDollars = Double.parseDouble(rep.getOfficeSold());
             double booksDollars = Double.parseDouble(rep.getBooksSold());
             double paperDollars = Double.parseDouble(rep.getPaperSold());
             total = officeDollars + booksDollars + paperDollars;
             isValid = true;
             txtError.setVisible(false);
        }
        catch (Exception e)
        {
            txtError.setText("Only dollar amounts are accepted");
            txtError.setVisible(true);
            isValid = false;
        }
        
        if(isValid)
        {
            //If everything is good, write the sales rep data to file.
              manager.addRecords(rep, "salesRep.txt");
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnEvaluateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEvaluateActionPerformed
    {//GEN-HEADEREND:event_btnEvaluateActionPerformed
        ArrayList<SalesRep> stars = new ArrayList<SalesRep>();
        stars = manager.evaluate("salesRep.txt");
        
        for(SalesRep rep : stars)
        {
            String outputString = String.format("Rep ID: %s\nFirst Name: %s\nLast Name: %s\nOffice Supplies: %s\nBooks: %s\nPaper: %s\nDistrict: %s\nContact Method: %s \n\n", rep.getRepID(), rep.getfName(), rep.getlName(), rep.getOfficeSold(), rep.getBooksSold(), rep.getPaperSold(), rep.getSalesDistrict(), rep.getContactMethod());
            outputText.append(outputString);
        }
    }//GEN-LAST:event_btnEvaluateActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDisplayActionPerformed
    {//GEN-HEADEREND:event_btnDisplayActionPerformed
        ArrayList<SalesRep> stars = new ArrayList<SalesRep>();
        stars = manager.evaluate("salesRep.txt");
        
        for(SalesRep rep : stars)
        {
            outputText.append(rep.toString());
        }
        
        manager.testMethod();
    }//GEN-LAST:event_btnDisplayActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnEvaluate;
    private javax.swing.JButton btnQuit;
    private javax.swing.JCheckBox checkEmail;
    private javax.swing.JCheckBox checkPhone;
    private javax.swing.JCheckBox checkVisit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea outputText;
    private javax.swing.JRadioButton salesButtonEast;
    private javax.swing.ButtonGroup salesButtonGroup;
    private javax.swing.JRadioButton salesButtonNorth;
    private javax.swing.JRadioButton salesButtonSouth;
    private javax.swing.JRadioButton salesButtonWest;
    private javax.swing.JScrollPane textArea;
    private javax.swing.JTextField txtBooksSold;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOfficeSold;
    private javax.swing.JTextField txtPaperSold;
    private javax.swing.JTextField txtRepID;
    // End of variables declaration//GEN-END:variables
}
